# Generated by Django 4.2.3 on 2024-09-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=100)),
                ('exchange_rate', models.CharField(max_length=100)),
                ('supported_services', models.TextField()),
            ],
        ),
    ]
