# Generated by Django 5.1 on 2024-09-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='supported_services',
        ),
        migrations.AddField(
            model_name='card',
            name='service',
            field=models.CharField(choices=[('udemy', 'Udemy'), ('apple_music', 'Apple Music'), ('spotify', 'Spotify'), ('netflix', 'Netflix'), ('amazon_prime', 'Amazon Prime'), ('google_play', 'Google Play Store'), ('uber', 'Uber'), ('paypal', 'PayPal'), ('ebay', 'eBay'), ('google_ads', 'Google Ads')], default='udemy', max_length=50),
        ),
    ]
