# Generated by Django 5.1 on 2024-09-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0002_remove_card_supported_services_card_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='card',
            name='service',
        ),
        migrations.AddField(
            model_name='card',
            name='services',
            field=models.ManyToManyField(to='forex.service'),
        ),
    ]
