# Generated by Django 5.1 on 2024-09-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0006_offer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.AddField(
            model_name='service',
            name='url',
            field=models.URLField(default='https://google.com'),
        ),
    ]
